.TH C2SIM "1" "Aug 2010" "C2SIM" "User Commands"
.SH NAME
c2sim \- codec2 testing framework
.SH DESCRIPTION
Codec2 test and evaluation program
.SH USAGE
c2sim 3200|2400|1600|1400}1300|1200 InputFile OutputRawFile [OPTIONS]
.SH OPTIONS
.TP
\fB\-\-help\fR
display help and exit
.TP
\fB\-\-rate\fR
Set rate
.TP
\fB\-\-gain\fR
Set gain
.TP
\fB\-\-lpc\fR
Set LPC model
.TP
\fB\-\-lspjnd\fR
set 
.TP
\fB\-\-lspmel\fR
set 
.TP
\fB\-\-lsp\fR
set 
.TP
\fB\-\-lspd\fR
set 
.TP
\fB\-\-lspvq\fR
set 
.TP
\fB\-\-lspres\fR
set 
.TP
\fB\-\-lspdt\fR
set 
.TP
\fB\-\-lspdt_mode\fR
set 
.TP
\fB\-\-lspjvm\fR
set 
.TP
\fB\-\-lspanssi\fR
set 
.TP
\fB\-\-phase0\fR
set 
.TP
\fB\-\-phaseexp\fR
set 
.TP
\fB\-\-ampexp\fR
set 
.TP
\fB\-\-postfilter\fR
set 
.TP
\fB\-\-hand_voicing\fR
set 
.TP
\fB\-\-dec\fR
set 
.TP
\fB\-\-dt\fR
set 
.TP
\fB\-\-hi\fR
set 
.TP
\fB\-\-simlpcpf\fR
set 
.TP
\fB\-\-lpcpf\fR
set 
.TP
\fB\-\-prede\fR
set 
.TP
\fB\-\-dump_pitch_e\fR
dumo pitch estimate
.TP
\fB\-\-sq_pitch_e\fR
scalar quantize pitch estimate
.TP
\fB\-\-vq_pitch_e\fR
vector quantize pitch estimate
.PP
Codec2 simulation.  Combines encoder and decoder and allows
switching in and out various algorithms and quantisation steps.
.BR
Used for algorithm development.
.SH "SEE ALSO"
.PP
c2dec(1) c2demo(1) c2enc(1) fdmdv_demod(1) fdmdv_interleave(1) fdmdv_mod(1) fdmdv_put_test_bits(1) fec_dec(1) fec_enc(1) insert_errors(1)
